# App Info
ios_app_id                                : 643541976

appstore_link                             : https://itunes.apple.com/jp/app/id643541976?mt=8
playstore_link                            : https://play.google.com/store/apps/details?id=com.jakkrokk.ilka&hl=ja
presskit_download_link                    : 

app_icon                                  : assets/DefaultIcon.png
app_name                                  : つながらないSNS ilka
app_price                                 : 無料
app_description                           : ilka は他人とつながるのではなく、自分の心との出会いを目指した、唯一のSNSです。

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : jakkrokk
your_link                                 : http://ilka.jakkrokk.com/
your_city                                 : Japan
email_address                             : app.jakkrokk+ilka@gmail.com
facebook_username                         :
instagram_username                        : 
twitter_username                          : jakkrokk
github_username                           : jakkrokk
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 2019/04/11
    description                           : いくつかバグフィックスを行いました
    fontawesome_icon_name                 : magic


# Theme Settings
topbar_color                              : "#07aaf4"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/1_20190411.png
cover_overlay_color                       : "#07aaf4"
cover_overlay_transparency                : 0.8

device_color                              : white

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
